baseURL = "https://niksa-fantela.web.app/"
languageCode = "en-us"
title = "Niksa Fantela"
theme="hugo-theme-cactus-plus"

[params]
    # My information
    author = "Nikša Fantela"
    description = "Personal web development blog"
    bio = "Javascript (Typescript) Developer from Croatia, currently deep into Angular & RxJS"
    copyright = "Copyright © 2020 Nikša Fantela"

    # Tools 
    enableSummary = true
    enableGoogleAnalytics = true
    enableTwitterCard = true

[social]
    twitter = "https://twitter.com/FantelaNiksa"
    github = "https://github.com/NFantela"